### ISSUE TITLE
link location of bootCode struture 

### ISSUE THREAD

**Issue by LGTMCU** [pulp-platform/boot-code#1]
[Pulpissimo platform]
When I do simulation under standalone mode, startup from internal boot_rom,
I notice that the core write “bootCode" based on address start from 0x1a0014e4, which is inside ROM section (spec link.ld), but udma try to read bootCode data start from 0x1c0014e4, which is inside L2RAM,

I think bootCode should be allocated inside of L2RAM, but infect it's inside of text section (objdump -t)
and as link.ld targeted, text/data section allocated into ROM (start from 0x1a000000).

Please help me to point where is the problem?

**Comment by haugoug** [comment]
Indeed bootCode should be in L2.
The cde file I've pushed was fine and was having the bootCode in L2 but the source code was wrong. I've just pushed a modif to fix what you report and generate the same cde as what is pushed in pulpissimo.

**Comment by LGTMCU** [comment]
works now. thank you very much!
